from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from sqlalchemy.orm import Session

from app.payroll.payslip_model import Payslip
from app.payroll.payslip_line_model import PayslipLine
from app.employees.model import Employee


def generate_payslip_pdf(
    db: Session,
    payslip_id: int
):
    payslip = (
        db.query(Payslip)
        .filter(Payslip.id == payslip_id)
        .first()
    )

    if not payslip:
        raise ValueError("Payslip not found")

    if payslip.status not in {"Finalized", "Paid"}:
        raise ValueError(
            "PDF can only be generated for Finalized or Paid payslips"
        )

    employee = (
        db.query(Employee)
        .filter(Employee.id == payslip.employee_id)
        .first()
    )

    lines = (
        db.query(PayslipLine)
        .filter(PayslipLine.payslip_id == payslip.id)
        .order_by(PayslipLine.sequence)
        .all()
    )

    buffer = BytesIO()

    pdf = canvas.Canvas(
        buffer,
        pagesize=A4
    )

    width, height = A4

    # Header
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(
        20 * mm,
        height - 25 * mm,
        "PeoplePay360"
    )

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(
        20 * mm,
        height - 38 * mm,
        "Employee Payslip"
    )

    # Employee information
    y = height - 55 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Employee:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        55 * mm,
        y,
        f"{employee.first_name} {employee.last_name}"
    )

    y -= 7 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Employee Code:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        55 * mm,
        y,
        employee.employee_code
    )

    y -= 7 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Pay Period:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        55 * mm,
        y,
        f"{payslip.period_start} to {payslip.period_end}"
    )

    y -= 7 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Status:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        55 * mm,
        y,
        payslip.status
    )

    # Salary table header
    y -= 15 * mm

    pdf.setFont("Helvetica-Bold", 10)

    pdf.drawString(20 * mm, y, "Code")
    pdf.drawString(50 * mm, y, "Salary Rule")
    pdf.drawString(130 * mm, y, "Category")
    pdf.drawRightString(190 * mm, y, "Amount")

    y -= 5 * mm

    pdf.line(
        20 * mm,
        y,
        190 * mm,
        y
    )

    y -= 7 * mm

    # Salary lines
    pdf.setFont("Helvetica", 9)

    for line in lines:

        pdf.drawString(
            20 * mm,
            y,
            line.code
        )

        pdf.drawString(
            50 * mm,
            y,
            line.name
        )

        pdf.drawString(
            130 * mm,
            y,
            line.category
        )

        pdf.drawRightString(
            190 * mm,
            y,
            f"Rs. {line.amount:,.2f}"
        )

        y -= 6 * mm

    # Totals
    y -= 8 * mm

    pdf.line(
        110 * mm,
        y,
        190 * mm,
        y
    )

    y -= 8 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(
        120 * mm,
        y,
        "Gross Salary:"
    )

    pdf.drawRightString(
        190 * mm,
        y,
        f"Rs. {payslip.gross_amount:,.2f}"
    )

    y -= 7 * mm

    pdf.drawString(
        120 * mm,
        y,
        "Deductions:"
    )

    pdf.drawRightString(
        190 * mm,
        y,
        f"Rs. {payslip.deduction_amount:,.2f}"
    )

    y -= 9 * mm

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(
        120 * mm,
        y,
        "Net Salary:"
    )

    pdf.drawRightString(
        190 * mm,
        y,
        f"Rs. {payslip.net_amount:,.2f}"
    )

    # Footer
    pdf.setFont("Helvetica", 8)
    pdf.drawString(
        20 * mm,
        15 * mm,
        "Generated by PeoplePay360 HR & Payroll"
    )

    pdf.save()

    buffer.seek(0)

    return buffer