"""add schedule to contracts

Revision ID: 0c602e8246e4
Revises: 85e4f4aba086
Create Date: 2026-09-05 14:14:07.961615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c602e8246e4'
down_revision: Union[str, Sequence[str], None] = '85e4f4aba086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'schedule_id')
    # ### end Alembic commands ###
