"""add schedule to employees

Revision ID: 85e4f4aba086
Revises: a68569a69340
Create Date: 2026-09-05 14:03:02.550761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e4f4aba086'
down_revision: Union[str, Sequence[str], None] = 'a68569a69340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'schedule_id')
    # ### end Alembic commands ###
