"""create salary rules table

Revision ID: 86275e2e6513
Revises: 46d45df7d473
Create Date: 2026-09-05 17:00:27.023833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86275e2e6513'
down_revision: Union[str, Sequence[str], None] = '46d45df7d473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_rules_code'), 'salary_rules', ['code'], unique=False)
    op.create_index(op.f('ix_salary_rules_id'), 'salary_rules', ['id'], unique=False)
    op.create_index(op.f('ix_salary_rules_salary_structure_id'), 'salary_rules', ['salary_structure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_rules_salary_structure_id'), table_name='salary_rules')
    op.drop_index(op.f('ix_salary_rules_id'), table_name='salary_rules')
    op.drop_index(op.f('ix_salary_rules_code'), table_name='salary_rules')
    op.drop_table('salary_rules')
    # ### end Alembic commands ###
