"""create payslips and payslip lines

Revision ID: 888c97c6c8da
Revises: ef88d0785fcd
Create Date: 2026-09-05 18:01:38.885828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888c97c6c8da'
down_revision: Union[str, Sequence[str], None] = 'ef88d0785fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payrun_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('basic_wage', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payslip_payrun_employee')
    )
    op.create_index(op.f('ix_payslips_contract_id'), 'payslips', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_index(op.f('ix_payslips_payrun_id'), 'payslips', ['payrun_id'], unique=False)
    op.create_index(op.f('ix_payslips_salary_structure_id'), 'payslips', ['salary_structure_id'], unique=False)
    op.create_table('payslip_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('salary_rule_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_lines_id'), 'payslip_lines', ['id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_payslip_id'), 'payslip_lines', ['payslip_id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_salary_rule_id'), 'payslip_lines', ['salary_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslip_lines_salary_rule_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_payslip_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_id'), table_name='payslip_lines')
    op.drop_table('payslip_lines')
    op.drop_index(op.f('ix_payslips_salary_structure_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payrun_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_contract_id'), table_name='payslips')
    op.drop_table('payslips')
    # ### end Alembic commands ###
