"""add salary structure to contracts

Revision ID: fd57bcb23eda
Revises: 86275e2e6513
Create Date: 2026-09-05 17:19:32.785839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd57bcb23eda'
down_revision: Union[str, Sequence[str], None] = '86275e2e6513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('salary_structure_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contracts_salary_structure_id'), 'contracts', ['salary_structure_id'], unique=False)
    op.create_foreign_key(None, 'contracts', 'salary_structures', ['salary_structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_index(op.f('ix_contracts_salary_structure_id'), table_name='contracts')
    op.drop_column('contracts', 'salary_structure_id')
    # ### end Alembic commands ###
